Repository Netflix/metaflow, pull requests merged in 2021-09, with the labels that each got.

#679 Representation change for `task.exception`
  metaflow/exception.py
  test/core/tests/task_exception.py
Labels: ok-to-test

#674 Fixes recursion error when METAFLOW_DEFAULT_ENVIRONMENT=conda
  metaflow/plugins/conda/conda_environment.py
Labels: ok-to-test

#689 Terminate task-level sidecars after `task_finished` hook has been executed
  metaflow/task.py
Labels: ok-to-test

#694 Only passdown parameters to datastore for the join step
  metaflow/task.py
Labels: ok-to-test

#695 Emit project related tags from within project decorator
  metaflow/cli.py
  metaflow/decorators.py
  metaflow/metadata/metadata.py
  metaflow/plugins/aws/step_functions/schedule_decorator.py
  metaflow/plugins/conda/conda_flow_decorator.py
  metaflow/plugins/project_decorator.py
  test/core/metaflow_extensions/plugins/flow_options.py
Labels: ok-to-test

#697 Datatools changes for convergence
  metaflow/datatools/s3.py
  metaflow/datatools/s3op.py
  metaflow/datatools/s3tail.py
  metaflow/datatools/s3util.py
  metaflow/plugins/aws/batch/batch.py
  metaflow/plugins/aws/batch/batch_cli.py
  metaflow/plugins/aws/batch/batch_decorator.py
Labels: ok-to-test

#698 Datatools changes from Convergence branch
  metaflow/datastore/s3.py
  metaflow/datastore/util/s3util.py
  metaflow/datatools/s3.py
Labels: ok-to-test

#700 Make the number of S3 retries configurable
  metaflow/datatools/s3.py
  metaflow/datatools/s3util.py
  metaflow/metaflow_config.py
Labels: ok-to-test

#702 Tag metadata with attempt_id
  metaflow/datastore/local.py
  metaflow/datastore/s3.py
  metaflow/metadata/metadata.py
  metaflow/plugins/aws/batch/batch_decorator.py
  metaflow/plugins/aws/step_functions/step_functions_decorator.py
  metaflow/plugins/conda/conda_step_decorator.py
  metaflow/plugins/metadata/local.py
  metaflow/plugins/metadata/service.py
  metaflow/runtime.py
  metaflow/task.py
Labels: ok-to-test

#692 [Breaking] Modify return type of created_at/finished_at to datetime
  metaflow/client/core.py
Labels: ok-to-test

#706 Conda _call_conda should print the stderr in case of error
  metaflow/plugins/conda/conda.py
Labels: ok-to-test

#593 Added preliminary documentation on the datastore
  docs/datastore.md
Labels: Convergence

#714 Final set of patches to convergence
  metaflow/cli.py
  metaflow/client/core.py
  metaflow/client/filecache.py
  metaflow/datastore/__init__.py
  metaflow/datastore/content_addressed_store.py
  metaflow/datastore/datastore_set.py
  metaflow/datastore/datastore_storage.py
  metaflow/datastore/exceptions.py
  metaflow/datastore/flow_datastore.py
  metaflow/datastore/local_storage.py
  metaflow/datastore/s3_storage.py
  metaflow/datastore/task_datastore.py
  metaflow/includefile.py
  metaflow/main_cli.py
  metaflow/metadata/util.py
  metaflow/mflog/__init__.py
  metaflow/mflog/save_logs.py
  metaflow/package.py
  metaflow/plugins/aws/batch/batch_cli.py
  metaflow/plugins/aws/batch/batch_decorator.py
  metaflow/plugins/conda/conda_step_decorator.py
  metaflow/plugins/metadata/local.py
  metaflow/util.py
Labels: ok-to-test

#580 New Datastore abstraction for Metaflow
  docs/datastore.md
  metaflow/cli.py
  metaflow/client/core.py
  metaflow/client/filecache.py
  metaflow/datastore/__init__.py
  metaflow/datastore/content_addressed_store.py
  metaflow/datastore/datastore.py
  metaflow/datastore/datastore_set.py
  metaflow/datastore/datastore_storage.py
  metaflow/datastore/exceptions.py
  metaflow/datastore/flow_datastore.py
  metaflow/datastore/inputs.py
  metaflow/datastore/local.py
  metaflow/datastore/local_storage.py
  metaflow/datastore/s3.py
  metaflow/datastore/s3_storage.py
  metaflow/datastore/task_datastore.py
  metaflow/datastore/util/__init__.py
  metaflow/datatools/__init__.py
  metaflow/decorators.py
  metaflow/includefile.py
  metaflow/main_cli.py
  metaflow/metadata/metadata.py
  metaflow/metadata/util.py
  metaflow/mflog/__init__.py
  metaflow/mflog/save_logs.py
  metaflow/package.py
  metaflow/plugins/aws/batch/batch_cli.py
  metaflow/plugins/aws/batch/batch_decorator.py
  metaflow/plugins/aws/step_functions/schedule_decorator.py
  metaflow/plugins/aws/step_functions/step_functions.py
  metaflow/plugins/aws/step_functions/step_functions_cli.py
  metaflow/plugins/aws/step_functions/step_functions_decorator.py
  metaflow/plugins/catch_decorator.py
  metaflow/plugins/conda/conda_environment.py
  metaflow/plugins/conda/conda_flow_decorator.py
  metaflow/plugins/conda/conda_step_decorator.py
  metaflow/plugins/metadata/local.py
  metaflow/plugins/package_cli.py
  metaflow/plugins/project_decorator.py
  metaflow/plugins/retry_decorator.py
  metaflow/plugins/timeout_decorator.py
  metaflow/runtime.py
  metaflow/task.py
  metaflow/util.py
Labels: Convergence, ok-to-test
