Repository Netflix/metaflow, pull requests merged in 2022-03, with the labels that each got.

#970 Emit app tag for AWS Batch jobs
  metaflow/plugins/aws/batch/batch.py
Labels: ok-to-test

#974 Bump to 2.5.3
  setup.py
Labels: ok-to-test

#979 Remove mflog references from plugins
  metaflow/mflog/__init__.py
  metaflow/mflog/redirect_streams.py
  metaflow/plugins/aws/batch/batch.py
  metaflow/plugins/aws/batch/batch_cli.py
  metaflow/plugins/aws/eks/kubernetes.py
  metaflow/plugins/aws/step_functions/step_functions.py
Labels: ok-to-test

#988 Use importlib_metadata 2.8.3 for Python 3.4, 3.5 but 4.8.3 for Python 3.6+
  metaflow/_vendor/v3_5/__init__.py
  metaflow/_vendor/v3_5/importlib_metadata.LICENSE
  metaflow/_vendor/v3_5/importlib_metadata/__init__.py
  metaflow/_vendor/v3_5/importlib_metadata/_compat.py
  metaflow/_vendor/v3_5/zipp.LICENSE
  metaflow/_vendor/v3_5/zipp.py
  metaflow/_vendor/v3_6/__init__.py
  metaflow/_vendor/v3_6/importlib_metadata.LICENSE
  metaflow/_vendor/v3_6/importlib_metadata/__init__.py
  metaflow/_vendor/v3_6/importlib_metadata/_adapters.py
  metaflow/_vendor/v3_6/importlib_metadata/_collections.py
  metaflow/_vendor/v3_6/importlib_metadata/_compat.py
  metaflow/_vendor/v3_6/importlib_metadata/_functools.py
  metaflow/_vendor/v3_6/importlib_metadata/_itertools.py
  metaflow/_vendor/v3_6/importlib_metadata/_meta.py
  metaflow/_vendor/v3_6/importlib_metadata/_text.py
  metaflow/_vendor/v3_6/importlib_metadata/py.typed
  metaflow/_vendor/v3_6/typing_extensions.LICENSE
  metaflow/_vendor/v3_6/typing_extensions.py
  metaflow/_vendor/v3_6/zipp.LICENSE
  metaflow/_vendor/v3_6/zipp.py
  metaflow/_vendor/vendor_any.txt
  metaflow/_vendor/vendor_v3_5.txt
  metaflow/_vendor/vendor_v3_6.txt
  metaflow/extension_support.py
  metaflow/vendor.py
Labels: ok-to-test

#991 Configurable temp root when pulling artifacts from s3
  metaflow/datastore/s3_storage.py
  metaflow/metaflow_config.py
Labels: mergeable

#987 Add an option to pass a `role` argument to S3() to provide a role
  metaflow/datatools/s3.py
  metaflow/datatools/s3op.py
  metaflow/datatools/s3util.py
  metaflow/plugins/aws/aws_client.py
Labels: ok-to-test, mergeable

#993 bump version to 2.5.4
  setup.py
Labels: ok-to-test
