Repository Netflix/metaflow, pull requests merged in 2022-10, with the labels that each got.

#1152 Pass datastore_type to validate_environment
  metaflow/cli.py
  metaflow/metaflow_environment.py
  metaflow/plugins/conda/conda_environment.py
  metaflow/task.py
Labels: ok-to-test

#1151 Remove message introduced in #1061
  metaflow/runtime.py
Labels: ok-to-test

#1144 Use json to dump/load decorator specs.
  metaflow/cli.py
  metaflow/debug.py
  metaflow/decorators.py
  metaflow/plugins/cards/card_decorator.py
  metaflow/plugins/conda/conda_step_decorator.py
Labels: ok-to-test, mergeable

#1163 argo use kubernetes client class
  metaflow/plugins/argo/argo_client.py
Labels: ok-to-test

#1109 Rewrite IncludeFile implementation
  metaflow/client/core.py
  metaflow/datastore/task_datastore.py
  metaflow/datatools/__init__.py
  metaflow/datatools/local.py
  metaflow/flowspec.py
  metaflow/includefile.py
  metaflow/parameters.py
  metaflow/plugins/airflow/airflow.py
  metaflow/plugins/airflow/airflow_cli.py
  metaflow/plugins/argo/argo_workflows_cli.py
  metaflow/plugins/aws/step_functions/step_functions_cli.py
  metaflow/plugins/azure/includefile_support.py
  test/core/metaflow_test/cli_check.py
  test/core/metaflow_test/metadata_check.py
  test/core/tests/basic_include.py
Labels: mergeable
