Repository Netflix/metaflow, pull requests merged in 2022-08, with the labels that each got.

#1076 Fix docstrings for the upcoming API reference (no functional changes!)
  metaflow/client/core.py
  metaflow/current.py
  metaflow/datatools/s3.py
  metaflow/flowspec.py
  metaflow/includefile.py
  metaflow/parameters.py
  metaflow/plugins/aws/batch/batch_decorator.py
  metaflow/plugins/aws/step_functions/schedule_decorator.py
  metaflow/plugins/cards/card_client.py
  metaflow/plugins/cards/card_decorator.py
  metaflow/plugins/cards/card_modules/card.py
  metaflow/plugins/cards/card_modules/components.py
  metaflow/plugins/cards/component_serializer.py
  metaflow/plugins/catch_decorator.py
  metaflow/plugins/conda/conda_flow_decorator.py
  metaflow/plugins/conda/conda_step_decorator.py
  metaflow/plugins/environment_decorator.py
  metaflow/plugins/kubernetes/kubernetes_decorator.py
  metaflow/plugins/project_decorator.py
  metaflow/plugins/resources_decorator.py
  metaflow/plugins/retry_decorator.py
  metaflow/plugins/timeout_decorator.py
Labels: ok-to-test

#1095 Move a sys.path modification in s3op to __main__
  metaflow/datatools/s3op.py
Labels: ok-to-test

#1094 Airflow Support
  metaflow/metaflow_config.py
  metaflow/plugins/__init__.py
  metaflow/plugins/airflow/__init__.py
  metaflow/plugins/airflow/airflow.py
  metaflow/plugins/airflow/airflow_cli.py
  metaflow/plugins/airflow/airflow_decorator.py
  metaflow/plugins/airflow/airflow_utils.py
  metaflow/plugins/airflow/dag.py
  metaflow/plugins/airflow/exception.py
  metaflow/plugins/airflow/plumbing/set_parameters.py
Labels: ok-to-test

#1098 Move sys.path insert earlier in s3op.py
  metaflow/datatools/s3op.py
Labels: ok-to-test

#1099 bump version to 2.7.4 for release
  setup.py
Labels: ok-to-test

#1100 Fix for env_escape bug when importing local packages
  metaflow/plugins/env_escape/__init__.py
Labels: ok-to-test

#1102 Bump to 2.7.5
  setup.py
Labels: ok-to-test, mergeable

#1105 Fix another issue with the escape hatch and paths
  metaflow/plugins/env_escape/__init__.py
Labels: ok-to-test

#1111 Fix an issue with get_cards not respecting a Task's ds-root
  metaflow/plugins/cards/card_client.py
Labels: mergeable

#1122 bump version to 2.7.7
  setup.py
Labels: ok-to-test
