Repository Netflix/metaflow, pull requests merged in 2022-12, with the labels that each got.

#1183 Clean up configuration variables
  metaflow/datatools/s3util.py
  metaflow/debug.py
  metaflow/extension_support.py
  metaflow/metadata/heartbeat.py
  metaflow/metaflow_config.py
  metaflow/metaflow_config_funcs.py
  metaflow/plugins/airflow/airflow.py
  metaflow/plugins/argo/argo_workflows.py
  metaflow/plugins/argo/argo_workflows_cli.py
  metaflow/plugins/aws/batch/batch.py
  metaflow/plugins/aws/step_functions/step_functions_cli.py
  metaflow/plugins/cards/card_client.py
  metaflow/plugins/cards/card_datastore.py
  metaflow/plugins/kubernetes/kubernetes.py
  metaflow/plugins/metadata/service.py
Labels: ok-to-test

#1186 Deal with transient errors (like SlowDowns) more effectively for S3
  metaflow/datatools/s3.py
  metaflow/datatools/s3op.py
  metaflow/datatools/s3util.py
  metaflow/metaflow_config.py
  metaflow/plugins/aws/aws_client.py
  test/data/s3/test_s3.py
Labels: ok-to-test, mergeable

#1206 Fix/move data files
  metaflow/__init__.py
  metaflow/cli.py
  metaflow/client/filecache.py
  metaflow/cmd/__init__.py
  metaflow/cmd/configure_cmd.py
  metaflow/cmd/main_cli.py
  metaflow/cmd/tutorials_cmd.py
  metaflow/cmd/util.py
  metaflow/datastore/__init__.py
  metaflow/extension_support.py
  metaflow/includefile.py
  metaflow/metadata/util.py
  metaflow/mflog/__init__.py
  metaflow/mflog/save_logs.py
  metaflow/plugins/__init__.py
  metaflow/plugins/airflow/airflow_cli.py
  metaflow/plugins/argo/argo_workflows_cli.py
  metaflow/plugins/aws/batch/batch.py
  metaflow/plugins/aws/batch/batch_decorator.py
  metaflow/plugins/aws/step_functions/step_functions.py
  metaflow/plugins/aws/step_functions/step_functions_cli.py
  metaflow/plugins/azure/includefile_support.py
  metaflow/plugins/cards/card_client.py
  metaflow/plugins/cards/card_datastore.py
  metaflow/plugins/conda/batch_bootstrap.py
  metaflow/plugins/conda/conda_step_decorator.py
  metaflow/plugins/datastores/__init__.py
  metaflow/plugins/datastores/azure_storage.py
  metaflow/plugins/datastores/gs_storage.py
  metaflow/plugins/datastores/local_storage.py
  metaflow/plugins/datastores/s3_storage.py
  metaflow/plugins/datatools/__init__.py
  metaflow/plugins/datatools/local.py
  metaflow/plugins/datatools/s3/__init__.py
  metaflow/plugins/datatools/s3/s3.py
  metaflow/plugins/datatools/s3/s3op.py
  metaflow/plugins/datatools/s3/s3tail.py
  metaflow/plugins/datatools/s3/s3util.py
  metaflow/plugins/gcp/includefile_support.py
  metaflow/plugins/kubernetes/kubernetes_decorator.py
  metaflow/plugins/metadata/local.py
  metaflow/task.py
  metaflow/util.py
  test/data/__init__.py
  test/data/s3/s3_data.py
  test/data/s3/test_s3.py
Labels: ok-to-test

#1210 Fix bug with datastore backend instantiation
  metaflow/plugins/conda/batch_bootstrap.py
Labels: ok-to-test

#1215 Reduce @environment arg length for step-functions create
  metaflow/plugins/aws/step_functions/step_functions.py
Labels: ok-to-test

#1207 Add support for Kubernetes tolerations
  metaflow/metaflow_config.py
  metaflow/plugins/argo/argo_workflows.py
  metaflow/plugins/kubernetes/kubernetes.py
  metaflow/plugins/kubernetes/kubernetes_cli.py
  metaflow/plugins/kubernetes/kubernetes_decorator.py
  metaflow/plugins/kubernetes/kubernetes_job.py
Labels: ok-to-test, mergeable

#1213 Fix CVE-2007-4559 (tar.extractall)
  metaflow/client/core.py
  metaflow/metadata/util.py
  metaflow/util.py
Labels: mergeable
